### ISSUE TITLE
Can't run FastMochi on H100 (runpod.io) - RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by morganavr** [hao-ai-lab/FastVideo#101]
I rented on runpod.io an H100 PCIe (80 GB VRAM, 188 GB RAM, 16vCPU) and followed an inference guide but got this error:

```
root@94c9e77e6444:/workspace/FastVideo# bash scripts/inference/inference_mochi_sp.sh
W1220 19:48:47.321000 1021 torch/distributed/run.py:793] 
W1220 19:48:47.321000 1021 torch/distributed/run.py:793] *****************************************
W1220 19:48:47.321000 1021 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1220 19:48:47.321000 1021 torch/distributed/run.py:793] *****************************************
world_size 4
world_size 4
world_size 4
Traceback (most recent call last):
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 176, in <module>
    main(args)
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 39, in main
    initialize_distributed()
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 31, in initialize_distributed
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 478, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

4
world_size 4
Traceback (most recent call last):
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 176, in <module>
    main(args)
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 39, in main
    initialize_distributed()
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 31, in initialize_distributed
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 478, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

Traceback (most recent call last):
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 176, in <module>
    main(args)
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 39, in main
    initialize_distributed()
  File "/workspace/FastVideo/fastvideo/sample/sample_t2v_mochi.py", line 31, in initialize_distributed
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 478, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

Loading pipeline components...:  60%|█████████████████████████████████████████████████████████████████████████████████████████████                                                              | 3/5 [00:00<00:00, 19.02it/sW1220 19:48:50.560000 1021 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1086 closing signal SIGTERM                                                                     | 1/4 [00:00<00:00,  9.20it/s]
W1220 19:48:50.566000 1021 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1087 closing signal SIGTERM
W1220 19:48:50.567000 1021 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1088 closing signal SIGTERM
E1220 19:48:50.694000 1021 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 3 (pid: 1089) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
fastvideo/sample/sample_t2v_mochi.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-20_19:48:50
  host      : 94c9e77e6444
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1089)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
root@94c9e77e6444:/workspace/FastVideo#

**Comment by jzhang38** [comment]
by default N_GPU is set to 4: https://github.com/hao-ai-lab/FastVideo/blob/a730e43d5f44c73ff316786cb92501e69b51919f/scripts/inference/inference_hunyuan.sh#L3

**Comment by morganavr** [comment]
Thanks, I have changed it to 1 but got OOM error. It seems that 80GB of VRAM is not enough for FastMochi.

**Comment by morganavr** [comment]
It works on H100 NVL (96GB of VRAM) but it takes 150 seconds to generate a single video.
