### ISSUE TITLE
Error with save_checkpoint when finetuning Mochi

### ISSUE THREAD

**Issue by hbb1** [hao-ai-lab/FastVideo#108]
Hi authors, 

Thank you for your great repo! It really helps!  

Recently, I am using 4 H800 (80GB) and 192GB of memory. I tried with `train_finetune_mochi_lora.sh`, and there were no problems.  However, I encountered an error with `train_finetune_mochi.sh`. The program will always hang in save_checkpoint and throw an error like:

```bash
Steps:   2%|▉                                  | 50/2000 [08:36<5:32:01, 10.22s/it, loss=0.7260, step_time=10.15s, grad_norm=0.898]/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:689: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
  warnings.warn(
/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:689: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
  warnings.warn(
/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:689: FutureWarning: FSDP.state_dict_type() and FSDP.set_state_dict_type() are being deprecated. Please use APIs, get_state_dict() and set_state_dict(), which can support different parallelisms, FSDP1, FSDP2, DDP. API doc: https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.get_state_dict .Tutorial: https://pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html .
  warnings.warn(
W1224 01:07:24.366000 140186497746752 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 5407 closing signal SIGTERM
W1224 01:07:24.367000 140186497746752 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 5408 closing signal SIGTERM
W1224 01:07:24.367000 140186497746752 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 5409 closing signal SIGTERM
E1224 01:07:24.982000 140186497746752 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -9) local_rank: 0 (pid: 5406) of binary: /public/home/huangbb1/anaconda3/envs/fastvideo/bin/python
Traceback (most recent call last):
  File "/public/home/huangbb1/anaconda3/envs/fastvideo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/public/home/huangbb1/anaconda3/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
fastvideo/train.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-24_01:07:24
  host      : server23
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 5406)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 5406
=====================================================
```

Do you know how to resolve it? Thank you!

**Comment by BrianChen1129** [comment]
Could you check if you have enough CPU memory? Especially saving with optimizer state

**Comment by hbb1** [comment]
Thank you! Increasing CPU memory solves this problem.
