### ISSUE TITLE
process terminates without cause

### ISSUE THREAD

**Issue by FuNian788** [hao-ai-lab/FastVideo#90]
When I try to run FastHunYuan, process terminates without cause. Hope for your reponse.
ENV: Torch 2.5.0+cu121, python 3.10.16. 

[lizexian.lzx@notebook-3ed686ac8089-worker-0 /home/lizexian.lzx/FastVideo]
$bash scripts/inference/inference_hunyuan.sh 
W1218 11:35:08.924000 49948 site-packages/torch/distributed/run.py:793] 
W1218 11:35:08.924000 49948 site-packages/torch/distributed/run.py:793] *****************************************
W1218 11:35:08.924000 49948 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1218 11:35:08.924000 49948 site-packages/torch/distributed/run.py:793] *****************************************
world_sizeworld_sizeworld_size  44 

4world_size
 4
4
Namespace(prompt='./assets/prompt.txt', num_frames=125, height=720, width=1280, num_inference_steps=6, model_path='data/FastHunyuan', output_path='outputs_video/hunyuan/cfg6/', fps=24, denoise_type='flow', seed=0, neg_prompt=None, guidance_scale=1.0, embedded_cfg_scale=6.0, flow_shift=17, batch_size=1, num_videos=1, load_key='module', use_cpu_offload=False, dit_weight='data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt', reproduce=False, disable_autocast=False, flow_reverse=True, flow_solver='euler', use_linear_quadratic_schedule=False, linear_schedule_end=25, model='HYVideo-T/2-cfgdistill', latent_channels=16, precision='bf16', rope_theta=256, vae='884-16c-hy', vae_precision='fp16', vae_tiling=True, text_encoder='llm', text_encoder_precision='fp16', text_states_dim=4096, text_len=256, tokenizer='llm', prompt_template='dit-llm-encode', prompt_template_video='dit-llm-encode-video', hidden_state_skip_layer=2, apply_final_norm=False, text_encoder_2='clipL', text_encoder_precision_2='fp16', text_states_dim_2=768, tokenizer_2='clipL', text_len_2=77)
2024-12-18 11:35:22.630 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:77 - Got text-to-video model root path: data/FastHunyuan
2024-12-18 11:35:22.630 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:93 - Building model...
4
Namespace(prompt='./assets/prompt.txt', num_frames=125, height=720, width=1280, num_inference_steps=6, model_path='data/FastHunyuan', output_path='outputs_video/hunyuan/cfg6/', fps=24, denoise_type='flow', seed=0, neg_prompt=None, guidance_scale=1.0, embedded_cfg_scale=6.0, flow_shift=17, batch_size=1, num_videos=1, load_key='module', use_cpu_offload=False, dit_weight='data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt', reproduce=False, disable_autocast=False, flow_reverse=True, flow_solver='euler', use_linear_quadratic_schedule=False, linear_schedule_end=25, model='HYVideo-T/2-cfgdistill', latent_channels=16, precision='bf16', rope_theta=256, vae='884-16c-hy', vae_precision='fp16', vae_tiling=True, text_encoder='llm', text_encoder_precision='fp16', text_states_dim=4096, text_len=256, tokenizer='llm', prompt_template='dit-llm-encode', prompt_template_video='dit-llm-encode-video', hidden_state_skip_layer=2, apply_final_norm=False, text_encoder_2='clipL', text_encoder_precision_2='fp16', text_states_dim_2=768, tokenizer_2='clipL', text_len_2=77)
2024-12-18 11:35:23.663 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:77 - Got text-to-video model root path: data/FastHunyuan
2024-12-18 11:35:23.663 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:93 - Building model...
4
Namespace(prompt='./assets/prompt.txt', num_frames=125, height=720, width=1280, num_inference_steps=6, model_path='data/FastHunyuan', output_path='outputs_video/hunyuan/cfg6/', fps=24, denoise_type='flow', seed=0, neg_prompt=None, guidance_scale=1.0, embedded_cfg_scale=6.0, flow_shift=17, batch_size=1, num_videos=1, load_key='module', use_cpu_offload=False, dit_weight='data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt', reproduce=False, disable_autocast=False, flow_reverse=True, flow_solver='euler', use_linear_quadratic_schedule=False, linear_schedule_end=25, model='HYVideo-T/2-cfgdistill', latent_channels=16, precision='bf16', rope_theta=256, vae='884-16c-hy', vae_precision='fp16', vae_tiling=True, text_encoder='llm', text_encoder_precision='fp16', text_states_dim=4096, text_len=256, tokenizer='llm', prompt_template='dit-llm-encode', prompt_template_video='dit-llm-encode-video', hidden_state_skip_layer=2, apply_final_norm=False, text_encoder_2='clipL', text_encoder_precision_2='fp16', text_states_dim_2=768, tokenizer_2='clipL', text_len_2=77)
2024-12-18 11:35:23.690 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:77 - Got text-to-video model root path: data/FastHunyuan
2024-12-18 11:35:23.690 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:93 - Building model...
4
Namespace(prompt='./assets/prompt.txt', num_frames=125, height=720, width=1280, num_inference_steps=6, model_path='data/FastHunyuan', output_path='outputs_video/hunyuan/cfg6/', fps=24, denoise_type='flow', seed=0, neg_prompt=None, guidance_scale=1.0, embedded_cfg_scale=6.0, flow_shift=17, batch_size=1, num_videos=1, load_key='module', use_cpu_offload=False, dit_weight='data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt', reproduce=False, disable_autocast=False, flow_reverse=True, flow_solver='euler', use_linear_quadratic_schedule=False, linear_schedule_end=25, model='HYVideo-T/2-cfgdistill', latent_channels=16, precision='bf16', rope_theta=256, vae='884-16c-hy', vae_precision='fp16', vae_tiling=True, text_encoder='llm', text_encoder_precision='fp16', text_states_dim=4096, text_len=256, tokenizer='llm', prompt_template='dit-llm-encode', prompt_template_video='dit-llm-encode-video', hidden_state_skip_layer=2, apply_final_norm=False, text_encoder_2='clipL', text_encoder_precision_2='fp16', text_states_dim_2=768, tokenizer_2='clipL', text_len_2=77)
2024-12-18 11:35:23.708 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:77 - Got text-to-video model root path: data/FastHunyuan
2024-12-18 11:35:23.709 | INFO     | fastvideo.models.hunyuan.inference:from_pretrained:93 - Building model...
2024-12-18 11:35:24.673 | INFO     | fastvideo.models.hunyuan.inference:load_state_dict:242 - Loading torch model data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt...
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/inference.py:248: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(
2024-12-18 11:35:24.700 | INFO     | fastvideo.models.hunyuan.inference:load_state_dict:242 - Loading torch model data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt...
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/inference.py:248: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(
2024-12-18 11:35:24.717 | INFO     | fastvideo.models.hunyuan.inference:load_state_dict:242 - Loading torch model data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt...
2024-12-18 11:35:24.717 | INFO     | fastvideo.models.hunyuan.inference:load_state_dict:242 - Loading torch model data/FastHunyuan/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt...
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/inference.py:248: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/inference.py:248: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(
2024-12-18 11:35:43.504 | INFO     | fastvideo.models.hunyuan.vae:load_vae:31 - Loading 3D VAE model (884-16c-hy) from: data/FastHunyuan/hunyuan-video-t2v-720p/vae
2024-12-18 11:35:43.517 | INFO     | fastvideo.models.hunyuan.vae:load_vae:31 - Loading 3D VAE model (884-16c-hy) from: data/FastHunyuan/hunyuan-video-t2v-720p/vae
2024-12-18 11:35:43.546 | INFO     | fastvideo.models.hunyuan.vae:load_vae:31 - Loading 3D VAE model (884-16c-hy) from: data/FastHunyuan/hunyuan-video-t2v-720p/vae
2024-12-18 11:35:43.606 | INFO     | fastvideo.models.hunyuan.vae:load_vae:31 - Loading 3D VAE model (884-16c-hy) from: data/FastHunyuan/hunyuan-video-t2v-720p/vae
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/vae/__init__.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(vae_ckpt, map_location=vae.device)
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/vae/__init__.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(vae_ckpt, map_location=vae.device)
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/vae/__init__.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(vae_ckpt, map_location=vae.device)
/home/lizexian.lzx/FastVideo/fastvideo/models/hunyuan/vae/__init__.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(vae_ckpt, map_location=vae.device)
2024-12-18 11:35:45.841 | INFO     | fastvideo.models.hunyuan.vae:load_vae:59 - VAE to dtype: torch.float16
2024-12-18 11:35:45.845 | INFO     | fastvideo.models.hunyuan.vae:load_vae:59 - VAE to dtype: torch.float16
2024-12-18 11:35:45.882 | INFO     | fastvideo.models.hunyuan.vae:load_vae:59 - VAE to dtype: torch.float16
2024-12-18 11:35:45.927 | INFO     | fastvideo.models.hunyuan.vae:load_vae:59 - VAE to dtype: torch.float16
2024-12-18 11:35:46.064 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:35:46.074 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:35:46.077 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:35:46.173 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (llm) from: data/FastHunyuan/text_encoder
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.09s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.09s/it]

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.09s/it]
2024-12-18 11:36:08.066 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:08.152 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:08.199 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:08.278 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:11.208 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:36:11.277 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:36:11.325 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:36:11.380 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (llm) from: data/FastHunyuan/text_encoder
2024-12-18 11:36:11.669 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:11.722 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:11.768 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:11.832 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:28 - Loading text encoder model (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:11.876 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:11.876 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:11.914 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:11.919 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:11.936 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:11.981 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:12.014 | INFO     | fastvideo.models.hunyuan.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.float16
2024-12-18 11:36:12.089 | INFO     | fastvideo.models.hunyuan.inference:predict:444 - Input (height, width, video_length) = (720, 1280, 125)
2024-12-18 11:36:12.089 | DEBUG    | fastvideo.models.hunyuan.inference:predict:502 - 
                        height: 720
                         width: 1280
                  video_length: 125
                        prompt: ['Will Smith casually eats noodles, his relaxed demeanor contrasting with the energetic background of a bustling street food market. The scene captures a mix of humor and authenticity. Mid-shot framing, vibrant lighting.']
                    neg_prompt: ['Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion']
                          seed: 0
                   infer_steps: 6
         num_videos_per_prompt: 1
                guidance_scale: 1.0
                      n_tokens: 460800
                    flow_shift: 17
       embedded_guidance_scale: 6.0
2024-12-18 11:36:12.090 | INFO     | fastvideo.models.hunyuan.inference:predict:444 - Input (height, width, video_length) = (720, 1280, 125)
2024-12-18 11:36:12.090 | DEBUG    | fastvideo.models.hunyuan.inference:predict:502 - 
                        height: 720
                         width: 1280
                  video_length: 125
                        prompt: ['Will Smith casually eats noodles, his relaxed demeanor contrasting with the energetic background of a bustling street food market. The scene captures a mix of humor and authenticity. Mid-shot framing, vibrant lighting.']
                    neg_prompt: ['Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion']
                          seed: 0
                   infer_steps: 6
         num_videos_per_prompt: 1
                guidance_scale: 1.0
                      n_tokens: 460800
                    flow_shift: 17
       embedded_guidance_scale: 6.0
2024-12-18 11:36:12.110 | INFO     | fastvideo.models.hunyuan.inference:predict:444 - Input (height, width, video_length) = (720, 1280, 125)
2024-12-18 11:36:12.111 | DEBUG    | fastvideo.models.hunyuan.inference:predict:502 - 
                        height: 720
                         width: 1280
                  video_length: 125
                        prompt: ['Will Smith casually eats noodles, his relaxed demeanor contrasting with the energetic background of a bustling street food market. The scene captures a mix of humor and authenticity. Mid-shot framing, vibrant lighting.']
                    neg_prompt: ['Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion']
                          seed: 0
                   infer_steps: 6
         num_videos_per_prompt: 1
                guidance_scale: 1.0
                      n_tokens: 460800
                    flow_shift: 17
       embedded_guidance_scale: 6.0
2024-12-18 11:36:12.124 | INFO     | fastvideo.models.hunyuan.text_encoder:load_tokenizer:64 - Loading tokenizer (clipL) from: data/FastHunyuan/text_encoder_2
2024-12-18 11:36:12.256 | INFO     | fastvideo.models.hunyuan.inference:predict:444 - Input (height, width, video_length) = (720, 1280, 125)
2024-12-18 11:36:12.256 | DEBUG    | fastvideo.models.hunyuan.inference:predict:502 - 
                        height: 720
                         width: 1280
                  video_length: 125
                        prompt: ['Will Smith casually eats noodles, his relaxed demeanor contrasting with the energetic background of a bustling street food market. The scene captures a mix of humor and authenticity. Mid-shot framing, vibrant lighting.']
                    neg_prompt: ['Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion']
                          seed: 0
                   infer_steps: 6
         num_videos_per_prompt: 1
                guidance_scale: 1.0
                      n_tokens: 460800
                    flow_shift: 17
       embedded_guidance_scale: 6.0
  0%|                                                                                                                                                                                               | 0/6 [00:00<?, ?it/s]W1218 11:36:15.647000 49948 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 50069 closing signal SIGTERM
W1218 11:36:15.943000 49948 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 50070 closing signal SIGTERM
W1218 11:36:15.943000 49948 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 50072 closing signal SIGTERM
E1218 11:36:31.543000 49948 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -8) local_rank: 2 (pid: 50071) of binary: /home/lizexian.lzx/.conda/envs/fastvideo/bin/python
Traceback (most recent call last):
  File "/home/lizexian.lzx/.conda/envs/fastvideo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/lizexian.lzx/.conda/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/lizexian.lzx/.conda/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/lizexian.lzx/.conda/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/lizexian.lzx/.conda/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lizexian.lzx/.conda/envs/fastvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
fastvideo/sample/sample_t2v_hunyuan.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-18_11:36:15
  host      : notebook-3ed686ac8089-worker-0
  rank      : 2 (local_rank: 2)
  exitcode  : -8 (pid: 50071)
  error_file: <N/A>
  traceback : Signal 8 (SIGFPE) received by PID 50071
=====================================================

**Comment by foreverpiano** [comment]
It seems like a initialize distributed API issue.
Make sure you have 4 GPUs and port 29503 is not being used.

https://github.com/hao-ai-lab/FastVideo/blob/e1b998b6ef76890f31cc46c711adf2d349cba400/scripts/inference/inference_hunyuan.sh#L3

Can you plot more infomation about the type and the number of GPUs you used and `pip freeze` output?

**Comment by FuNian788** [comment]
I have 8 h20 gpus and I just use 4 of them.
When I discard  DDP and use 1 gpu in the way of `python fastvideo/sample/sample_t2v_hunyuan.py`, it raises an Error: scripts/inference/inference_hunyuan.sh: line 20: 73762 Floating point exception(core dumped) python fastvideo/sample/sample_t2v_hunyuan.py --height 720 --width 1280 --num_frames 125 --num_inference_steps 6 --guidance_scale 1 --embedded_cfg_scale 6 --flow_shift 17 --flow-reverse --prompt ./assets/prompt.txt --seed 1024 --output_path outputs_video/hunyuan/cfg6/ --model_path $MODEL_BASE --dit-weight ${MODEL_BASE}/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt

I don't know what causes core dumped.


PIP:

$pip freeze
absl-py==2.1.0
accelerate==1.0.1
addict==2.4.0
aiofiles==23.2.1
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.2
albucore==0.0.19
albumentations==1.4.20
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.7.0
async-timeout==5.0.1
attrs==24.3.0
av==13.1.0
beautifulsoup4==4.12.3
blessed==1.20.0
certifi==2024.12.14
charset-normalizer==3.4.0
click==8.1.7
contourpy==1.3.1
cycler==0.12.1
decorator==4.4.2
decord==0.6.0
deepspeed==0.9.3
diffusers==0.30.2
docker-pycreds==0.4.0
einops==0.8.0
eval_type_backport==0.2.0
exceptiongroup==1.2.2
fastapi==0.115.3
-e git+https://github.com/hao-ai-lab/FastVideo.git@e1b998b6ef76890f31cc46c711adf2d349cba400#egg=fastvideo
ffmpy==0.4.0
filelock==3.13.1
flake8==7.1.1
flash-attn==2.7.0.post2
fonttools==4.55.3
frozenlist==1.5.0
fsspec==2024.2.0
ftfy==6.3.0
future==1.0.0
fvcore==0.1.5.post20221221
gdown==5.2.0
gitdb==4.0.11
GitPython==3.1.43
gpustat==1.1.1
gradio==5.3.0
gradio_client==1.4.2
grpcio==1.68.1
h11==0.14.0
h5py==3.12.1
httpcore==1.0.7
httpx==0.28.1
huggingface-hub==0.26.1
idna==3.6
imageio==2.36.0
imageio-ffmpeg==0.5.1
importlib_metadata==8.5.0
iopath==0.1.10
Jinja2==3.1.3
joblib==1.4.2
kiwisolver==1.4.7
liger_kernel==0.4.1
lightning-utilities==0.11.9
loguru==0.7.3
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mccabe==0.7.0
mdurl==0.1.2
mmcv==1.7.0
moviepy==1.0.3
mpmath==1.3.0
multidict==6.1.0
networkx==3.2.1
ninja==1.11.1.3
numpy==1.26.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==12.560.30
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.1.105
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
orjson==3.10.12
packaging==24.2
pandas==2.2.3
parameterized==0.9.0
peft==0.13.2
pillow==10.2.0
platformdirs==4.3.6
portalocker==3.0.0
proglog==0.1.10
propcache==0.2.1
protobuf==5.28.3
psutil==6.1.0
ptflops==0.7.4
pycodestyle==2.12.1
pydantic==2.9.2
pydantic_core==2.23.4
pydub==0.25.1
pyflakes==3.2.0
Pygments==2.18.0
pyparsing==3.2.0
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-multipart==0.0.20
pytorch-lightning==2.4.0
pytorchvideo==0.1.5
pytz==2024.2
PyYAML==6.0.1
regex==2024.9.11
requests==2.31.0
rich==13.9.4
rotary-embedding-torch==0.8.5
ruff==0.8.3
safetensors==0.4.5
scikit-learn==1.5.2
scikit-video==1.1.11
scipy==1.14.1
semantic-version==2.10.0
sentencepiece==0.2.0
sentry-sdk==2.19.2
setproctitle==1.3.4
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.6
starlette==0.41.3
stringzilla==3.11.1
sympy==1.13.1
tabulate==0.9.0
tensorboard==2.18.0
tensorboard-data-server==0.7.2
termcolor==2.5.0
test_tube==0.7.5
threadpoolctl==3.5.0
timm==1.0.11
tokenizers==0.20.1
tomlkit==0.12.0
torch==2.5.0+cu121
torchdiffeq==0.2.4
torchmetrics==1.5.1
torchvision==0.20.0+cu121
tqdm==4.66.5
transformers==4.46.1
triton==3.1.0
typer==0.15.1
typing_extensions==4.9.0
tzdata==2024.2
urllib3==2.2.0
uvicorn==0.32.0
wandb==0.18.5
watch==0.2.7
wcwidth==0.2.13
websockets==12.0
Werkzeug==3.1.3
yacs==0.1.8
yapf==0.32.0
yarl==1.18.3
zipp==3.21.0

**Comment by jzhang38** [comment]
@FuNian788 Do you have enough CPU memory?Could you try agian with at least 192G CPU memory? Alternatively you can try docker https://hub.docker.com/repository/docker/py0077/fastvideo/general

**Comment by foreverpiano** [comment]
Another possible reason: referring to [issue #32](https://github.com/aigc-apps/EasyAnimate/issues/32), it seems that H20 may have bad support for bf16.
So one option is to perform inference in fp16.  Try to add --precision fp16 in the script.

**Comment by BrianChen1129** [comment]
Could you try agian with at least 192G CPU memory?

**Comment by FuNian788** [comment]
@foreverpiano I tried --precision fp16 but it does not work..

**Comment by FuNian788** [comment]
@jzhang38 I am sure I have enough CPU memory.. Considering my machine and env, I may try docker at the end

**Comment by foreverpiano** [comment]
@FuNian788 I am trying to reproduce it on H20. I don't have this GPU now, so I need to wait a bit while I go borrow one from the platform. I think the docker should solve the problem you have.

**Comment by FuNian788** [comment]
@foreverpiano Good news, follow the same process, I can generate videos correctly on 4 A100 GPUs (even not use --precision fp16), so the problem may be located in the difference between GPUs. 
However, used H20 / A100 GPUs are on different clusters, so the problem of our internal environment and dependence can not be completely ruled out. Hope for your reponse, and I am glad to explore and solve it with you
