### ISSUE TITLE
No module named 'fastvideo'

### ISSUE THREAD

**Issue by TZYSJTU** [hao-ai-lab/FastVideo#99]
why cannot import it？
[2024-12-20 12:23:41,363] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "fastvideo/sample/sample_t2v_hunyuan.py", line 15, in <module>
    from fastvideo.models.hunyuan.utils.file_utils import save_videos_grid
ModuleNotFoundError: No module named 'fastvideo'
Traceback (most recent call last):
  File "fastvideo/sample/sample_t2v_hunyuan.py", line 15, in <module>
    from fastvideo.models.hunyuan.utils.file_utils import save_videos_grid
ModuleNotFoundError: No module named 'fastvideo'

**Comment by jzhang38** [comment]
make sure you pip install -e .

**Comment by TZYSJTU** [comment]
well，in a new conda env this was solved

**Comment by TZYSJTU** [comment]
thanks
